### ISSUE TITLE
Missing conflict.content option on this.dest.write

### ISSUE THREAD

**Issue by endorama** [gillesfabio/yeoman-blender#1]
Hello,
I'm experiencing an issue using yeoman-blender.

[This is](http://pastebin.com/TLUr9FUx) my index.js file. This code is currectly working if used directly in the index.js file.

And this is the issue:

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: Missing conflict.content option
    at Conflicter.add (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/lib/util/conflicter.js:28:3)
    at checkForCollision (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/lib/actions/actions.js:248:19)
    at Object.checkForCollisionFilter (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/lib/base.js:644:10)
    at runAsync (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:152:26)
    at Env.applyValidationFilters (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:129:3)
    at Env.applyWriteFilters (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:90:21)
    at Env.write (/home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/node_modules/file-utils/lib/env.js:37:17)
    at module.exports.gitFiles (/home/endorama/code/github/endorama/generator-ng-lift/app/flavors/base/writing.js:44:15)
    at /home/endorama/code/github/endorama/generator-ng-lift/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

Offending line is:

``` js
this.dest.write('app/components/.gitkeep');
```

Any hint on how to solve this?

**Comment by endorama** [comment]
I'm sorry, my bad for opening this issue. After further tests the problem was not related with blender in any way.

Thanks for this marvelous module :)

Cheers
